name: Upload
description: Upload result symlink closure to binary cache
runs:
  using: composite
  steps:
    - name: Upload
      shell: bash
      run: TMPDIR="$HOME/tmp" nix copy ./result --to 's3://cache.splitleaf.de?endpoint=api.s3.splitleaf.de&region=garage'
