keys:
  - &admin age1mpq8m4p7dnxh5ze3fh7etd2k6sp85zdnmp9te3e9chcw4pw07pcq960zh5

  # Hosts
  - &alto age1qz04yg4h4g22wxqca2pd5k0z574223f6m5c9jy5ny37nlgcd6u4styf06t
  - &cirrus age1dnpwfwh0h95r63e5qfjc2gvffw2tr2tx4new7sq2h3qs90kx9fmq322mx4
  - &cumulus age1dnru7l0agvnw3t9kmx60u4vh5u4tyd49xdve53zspxkznnp9f34qtec9dl
  - &fern age1sywwrwse76x8yskrsfpwk38fu2cmyx5s9qkf2pgc68cta0vj9psql7dp6e
  - &north age18x6herevmcuhcmeh47ll6p9ck9zk4ga6gfxwlc8yl49rwjxm7qusylwfgc

  # Users
  - &seb-fern age190mf9wx4ct7qvne3ly9j3cj9740z5wnfhsl6vsc5wtfyc5pueuas9hnjtr
  - &seb-north age1p32cyzakxtcx346ej82ftln4r2aw2pcuazq3583s85nzsan4ygqsj32hjf

creation_rules:
  # Hosts
  - path_regex: hosts/alto/secrets.json$
    key_groups:
      - age:
          - *admin
          - *alto
  - path_regex: hosts/cirrus/secrets.json$
    key_groups:
      - age:
          - *admin
          - *cirrus
  - path_regex: hosts/cumulus/secrets.json$
    key_groups:
      - age:
          - *admin
          - *cumulus
  - path_regex: hosts/fern/secrets.json$
    key_groups:
      - age:
          - *admin
          - *fern
  - path_regex: hosts/north/secrets.json$
    key_groups:
      - age:
          - *admin
          - *north

  # Users
  - path_regex: users/seb/@fern/secrets.json$
    key_groups:
      - age:
          - *admin
          - *seb-fern
  - path_regex: users/seb/@north/secrets.json$
    key_groups:
      - age:
          - *admin
          - *seb-north
