keys:
  - &admin age1mpq8m4p7dnxh5ze3fh7etd2k6sp85zdnmp9te3e9chcw4pw07pcq960zh5

  # Hosts
  - &north age18x6herevmcuhcmeh47ll6p9ck9zk4ga6gfxwlc8yl49rwjxm7qusylwfgc
  - &inspiron age1jl9s4vp78wuwymjxaje6fg4ax0gg5aq8pn8khfmtn5rvap0d83tqfr05dv
  - &fern age1sywwrwse76x8yskrsfpwk38fu2cmyx5s9qkf2pgc68cta0vj9psql7dp6e
  - &stratus age1pryafed9elaea6zk5gnf6drjt4nznc02385y973lwt9t2s7j7vmsfnggkp

  # Users
  - &seb-north age1p32cyzakxtcx346ej82ftln4r2aw2pcuazq3583s85nzsan4ygqsj32hjf
  - &seb-inspiron age1s9h9hh8f0vudwn4awr90mj0ka2xh9gppwus0jmvmaz3j3uckz94s36gzkz
  - &seb-fern age190mf9wx4ct7qvne3ly9j3cj9740z5wnfhsl6vsc5wtfyc5pueuas9hnjtr

creation_rules:
  # Hosts
  - path_regex: hosts/north/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *north
  - path_regex: hosts/inspiron/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *inspiron
  - path_regex: hosts/fern/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *fern
  - path_regex: hosts/stratus/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *stratus

  # Users
  - path_regex: users/seb/@north/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *seb-north
  - path_regex: users/seb/@inspiron/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *seb-inspiron
  - path_regex: users/seb/@fern/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *seb-fern
