keys:
  # Hosts
  - &alto age1qz04yg4h4g22wxqca2pd5k0z574223f6m5c9jy5ny37nlgcd6u4styf06t
  - &fern age1sywwrwse76x8yskrsfpwk38fu2cmyx5s9qkf2pgc68cta0vj9psql7dp6e
  - &north age18x6herevmcuhcmeh47ll6p9ck9zk4ga6gfxwlc8yl49rwjxm7qusylwfgc
  - &stratus age1pryafed9elaea6zk5gnf6drjt4nznc02385y973lwt9t2s7j7vmsfnggkp

  # Users
  - &seb-admin age1mpq8m4p7dnxh5ze3fh7etd2k6sp85zdnmp9te3e9chcw4pw07pcq960zh5
  - &seb-fern age190mf9wx4ct7qvne3ly9j3cj9740z5wnfhsl6vsc5wtfyc5pueuas9hnjtr
  - &seb-north age1p32cyzakxtcx346ej82ftln4r2aw2pcuazq3583s85nzsan4ygqsj32hjf

creation_rules:
  # Hosts
  - path_regex: hosts/alto/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *alto
  - path_regex: hosts/fern/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *fern
  - path_regex: hosts/north/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *north
  - path_regex: hosts/stratus/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *stratus

  # Users
  - path_regex: users/seb/@fern/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *seb-fern
  - path_regex: users/seb/@north/secrets.yaml$
    key_groups:
      - age:
          - *seb-admin
          - *seb-north
