keys:
  - &admin age1mpq8m4p7dnxh5ze3fh7etd2k6sp85zdnmp9te3e9chcw4pw07pcq960zh5

  # Hosts
  - &north age18x6herevmcuhcmeh47ll6p9ck9zk4ga6gfxwlc8yl49rwjxm7qusylwfgc
  - &inspiron age1jl9s4vp78wuwymjxaje6fg4ax0gg5aq8pn8khfmtn5rvap0d83tqfr05dv
  - &stratus age1pryafed9elaea6zk5gnf6drjt4nznc02385y973lwt9t2s7j7vmsfnggkp

  # Containers
  - &forgejo age12k607dpdjt5dyq0w3hpgyfdyfrrfuutxgra0tgt8qja30er7cupsfps60n
  - &nextcloud age1jutruntzdaqs26mpe68pafje23m9n4klm04fva05fcdyvyqnaamsvqf3jr
  - &paperless age1y82j460w5fh0fpquatqar0zqet0vzzfzjnegrp686na3gejapdtsc37vuh

  # Users
  - &seb-north age1p32cyzakxtcx346ej82ftln4r2aw2pcuazq3583s85nzsan4ygqsj32hjf
  - &seb-inspiron age1s9h9hh8f0vudwn4awr90mj0ka2xh9gppwus0jmvmaz3j3uckz94s36gzkz

creation_rules:
  # Hosts
  - path_regex: hosts/north/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *north
  - path_regex: hosts/inspiron/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *inspiron
  - path_regex: hosts/stratus/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *stratus

  # Containers
  - path_regex: hosts/stratus/containers/nspawn/forgejo/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *forgejo
  - path_regex: hosts/stratus/containers/nspawn/nextcloud/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *nextcloud
  - path_regex: hosts/stratus/containers/nspawn/paperless/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *paperless

  # Users
  - path_regex: users/seb/@north/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *seb-north
  - path_regex: users/seb/@inspiron/secrets.yaml$
    key_groups:
      - age:
          - *admin
          - *seb-inspiron
