name: "Check & Test"
on:
  workflow_call:

jobs:
  parse-flake:
    runs-on: nixos
    outputs:
      checks: ${{ steps.checks.outputs.checks }}
      tests: ${{ steps.tests.outputs.tests }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          persist-credentials: false
      - name: Get checks
        id: checks
        run: |
          checks=$(nix eval .#checks.x86_64-linux --apply builtins.attrNames --json)
          printf "checks=%s" "$checks" >> "$FORGEJO_OUTPUT"
      - name: Get tests
        id: tests
        run: |
          tests=$(nix eval .#tests.x86_64-linux --apply builtins.attrNames --json)
          printf "tests=%s" "$tests" >> "$FORGEJO_OUTPUT"

  build-check:
    needs: parse-flake
    runs-on: nixos
    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJSON(needs.parse-flake.outputs.checks) }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        uses: ./.forgejo/actions/build
        with:
          flake-output: .#checks.x86_64-linux.${{ matrix.check }}
      - name: Upload
        uses: ./.forgejo/actions/upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}

  build-test:
    needs: parse-flake
    runs-on: nixos
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.parse-flake.outputs.tests) }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
        with:
          persist-credentials: false
      - name: Build
        uses: ./.forgejo/actions/build
        with:
          flake-output: .#tests.x86_64-linux.${{ matrix.test }}
      - name: Upload
        uses: ./.forgejo/actions/upload
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
