name: "CI"
on:
  workflow_dispatch:
  push:
    branches: [main]
concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: true
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
jobs:
  parse-flake:
    runs-on: nixos
    outputs:
      checks: ${{ steps.checks.outputs.checks }}
      servers: ${{ steps.servers.outputs.servers }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Get checks
        id: checks
        run: |
          checks=$(nix eval .#checks.x86_64-linux --apply builtins.attrNames --json)
          printf "checks=%s" "$checks" >> "$FORGEJO_OUTPUT"
      - name: Get servers
        id: servers
        run: |
          servers=$(nix eval .#nixosConfigurations --apply 'configs:
            configs
            |> builtins.attrNames
            |> builtins.filter (hostName: configs.${hostName}.config.custom.services.deploy-webhook.enable)
          ' --json)
          printf "servers=%s" "$servers" >> "$FORGEJO_OUTPUT"
  build-check:
    needs: parse-flake
    runs-on: nixos
    strategy:
      fail-fast: false
      matrix:
        check: ${{ fromJSON(needs.parse-flake.outputs.checks) }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Build
        uses: ./.forgejo/actions/build
        with:
          flake-output: .#checks.x86_64-linux.${{ matrix.check }}
      - name: Upload
        uses: ./.forgejo/actions/upload
  build-server:
    needs: parse-flake
    runs-on: nixos
    strategy:
      fail-fast: false
      matrix:
        server: ${{ fromJSON(needs.parse-flake.outputs.servers) }}
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Build
        uses: ./.forgejo/actions/build
        with:
          flake-output: .#nixosConfigurations.${{ matrix.server }}.config.system.build.toplevel
      - name: Upload
        uses: ./.forgejo/actions/upload
  deploy:
    needs: [parse-flake, build-check, build-server]
    runs-on: nixos
    strategy:
      fail-fast: false
      matrix:
        server: ${{ fromJSON(needs.parse-flake.outputs.servers) }}
    steps:
      - name: Deploy
        timeout-minutes: 10
        run: curl --fail-with-body https://${{ matrix.server }}.splitleaf.de/hooks/deploy
  notify:
    if: always()
    needs: [deploy]
    runs-on: nixos
    steps:
      - name: Notify success
        if: needs.deploy.result == 'success'
        env:
          SHA: ${{ forgejo.sha }}
          COMMIT_MSG: ${{ forgejo.event.head_commit.message }}
        run: |
          body=$(printf 'Commit `%s` deployed successfully.\n> %s' "${SHA::7}" "${COMMIT_MSG%%$'\n'*}")
          curl -s \
            -H "Title: CI: Deployment succeeded" \
            -H "Priority: low" \
            -H "Tags: white_check_mark" \
            -H "Actions: view, Open workflow run, ${{ forgejo.server_url }}/${{ forgejo.repository }}/actions/runs/${{ forgejo.run_id }}" \
            -H "Markdown: yes" \
            -d "$body" \
            https://ntfy.sh/splitleaf
      - name: Notify failure
        if: needs.deploy.result == 'failure' || needs.deploy.result == 'skipped'
        env:
          SHA: ${{ forgejo.sha }}
          COMMIT_MSG: ${{ forgejo.event.head_commit.message }}
        run: |
          body=$(printf 'Commit `%s` failed to deploy.\n> %s' "${SHA::7}" "${COMMIT_MSG%%$'\n'*}")
          curl -s \
            -H "Title: CI: Deployment failed" \
            -H "Priority: default" \
            -H "Tags: rotating_light" \
            -H "Actions: view, Open workflow run, ${{ forgejo.server_url }}/${{ forgejo.repository }}/actions/runs/${{ forgejo.run_id }}" \
            -H "Markdown: yes" \
            -d "$body" \
            https://ntfy.sh/splitleaf
