name: "PR Checks"
on:
  pull_request:

concurrency:
  group: ${{ forgejo.workflow }}-${{ forgejo.ref }}
  cancel-in-progress: true

jobs:
  build-checks-and-tests:
    if: >-
      ${{
        forgejo.event.pull_request.base.ref == 'main' &&
        forgejo.event.pull_request.head.repo.full_name == forgejo.repository &&
        forgejo.event.pull_request.head.ref == 'automation/flake-update'
      }}
    uses: ./.forgejo/workflows/check-test.yml
    secrets:
      S3_KEY_ID: ${{ secrets.S3_KEY_ID }}
      S3_SECRET_KEY: ${{ secrets.S3_SECRET_KEY }}
