name: "Update"
on:
  schedule:
    - cron: "0 4 * * 2,6"
  workflow_dispatch:
jobs:
  update:
    runs-on: nixos
    steps:
      - name: Checkout
        uses: https://code.forgejo.org/actions/checkout@v4
      - name: Configure git user
        run: |
          git config --local user.name "forgejo-actions[bot]"
          git config --local user.email "forgejo-actions[bot]@noreply.codeberg.org"
      - name: Update
        run: nix flake update --commit-lock-file
      - name: Push
        run: git push
