{
    imports = [
        ./flatpak.nix
        ./vm.nix
        ./wlan.nix
        ./doas.nix
        ./vpn.nix
        ./comma.nix
        ./auto-gc.nix
        ./sops.nix
        ./bluetooth.nix
        ./auto-cpufreq.nix
        ./x-input.nix
        ./de.nix
        ./dm.nix
        ./sound.nix
        ./boot-loader.nix
        ./nix-helper.nix
    ];
}
